name: Meow
version: '${project.version}'
main: com.aurates.boop.BoopPlugin
api-version: '1.21'
commands:
  meow:
    description: Send a meow message privately
    usage: /meow <player>
    aliases:
      - m
